enhance: initial solution for namespaced xml tags
dmariel/scrapy pull request #39
Opened 2021-03-02 13:38 UTC by kazaaz

Co-authored-by: alkazaz alkazaz@kth.se
Co-authored-by: swill swill@kth.se
Co-authored-by: lerjevik lerjevik@kth.se
Co-authored-by: djiar djiar@kth.se
Co-authored-by: aljica aljica@kth.se

2021-03-03 13:58 UTC, djikoSal requested changes
Not entirely correct

2021-03-03 13:58 UTC, djikoSal commented on tests/test_utils_iterators.py
> -
This should not be deleted

2021-03-03 17:00 UTC, djikoSal requested changes

2021-03-03 17:00 UTC, djikoSal commented on scrapy/utils/iterators.py
> +        return obj.text.replace(old, new)
```suggestion
        return obj.replace(body=obj.text.replace(old, new))
```
```suggestion
        return obj.text.replace(old, new)
```

2021-03-03 17:00 UTC, djikoSal commented on scrapy/utils/iterators.py
> +        return str(obj).replace(old, new)
```suggestion
        return obj.decode().replace(old, new).encode()
```
```suggestion
        return str(obj).replace(old, new)
```

2021-03-03 17:00 UTC, djikoSal commented on scrapy/utils/iterators.py
> +        nodename_sanitized =  nodename.replace(":", "-")
Perhaps re-use our _replace_all here?

2021-03-05 07:18 UTC, kazaaz commented on tests/test_utils_iterators.py
> -
Should be fixed now!

2021-03-05 07:57 UTC, djikoSal reviewed
Looks good now!

2021-03-05 07:58 UTC, djikoSal approved these changes

2024-11-18 12:11 UTC, closed without merging